# What Is Pytorch?

**It’s a Python-based scientific computing package targeted at two sets of audiences:**

- A replacement for NumPy to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

## Tensors

### 0. import related libraries

In [10]:

from __future__ import print_function
import torch
import numpy as np

### 1. Construct a 5x3 matrix, uninitialized

In [11]:
x = torch.empty(5, 3)
print("x = ", x)
print("type(x) = ", type(x))

x =  tensor([[3.7835e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
type(x) =  <class 'torch.Tensor'>


### 2. Construct a randomly initialized matrix

In [13]:
x = torch.rand(5, 3)
print("x = ", x)
print("type(x) = ", type(x))
print("x.shape = ", x.shape)

x =  tensor([[0.5919, 0.6541, 0.0529],
        [0.7565, 0.9774, 0.8976],
        [0.5468, 0.9181, 0.0719],
        [0.3269, 0.2011, 0.9200],
        [0.6695, 0.8901, 0.9494]])
type(x) =  <class 'torch.Tensor'>
x.shape =  torch.Size([5, 3])


### 3. Construct a matrix filled zeros or ones and of dtype long

In [14]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [21]:
x = torch.ones(5, 3, dtype=torch.int)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


### 4. Construct a tensor directly from data

In [19]:
x = torch.tensor([5.5, 3])
print(x)
print(x.size())

tensor([5.5000, 3.0000])
torch.Size([2])


## Operations

### 1. Addition: syntax 1

In [24]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[0.4591, 1.3808, 1.5558],
        [1.8423, 1.6681, 1.2942],
        [0.9488, 1.3735, 0.7611],
        [1.2599, 1.0841, 0.4150],
        [1.4242, 1.5026, 1.2056]])


### 2. Addition: syntax 2

In [26]:
print(torch.add(x, y))

tensor([[0.4591, 1.3808, 1.5558],
        [1.8423, 1.6681, 1.2942],
        [0.9488, 1.3735, 0.7611],
        [1.2599, 1.0841, 0.4150],
        [1.4242, 1.5026, 1.2056]])


**The result of "+" is the same as add()**

### 3. Addition: providing an output tensor as argument

In [27]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.4591, 1.3808, 1.5558],
        [1.8423, 1.6681, 1.2942],
        [0.9488, 1.3735, 0.7611],
        [1.2599, 1.0841, 0.4150],
        [1.4242, 1.5026, 1.2056]])


### 4. Addition: in-place

In [28]:
# adds x to y
y.add_(x)
print(y)

tensor([[0.4591, 1.3808, 1.5558],
        [1.8423, 1.6681, 1.2942],
        [0.9488, 1.3735, 0.7611],
        [1.2599, 1.0841, 0.4150],
        [1.4242, 1.5026, 1.2056]])


### 5. Index

In [31]:
print("x = ", x)
# All rows, Column 1
print("x[:, 1] = ", x[:, 1])

x =  tensor([[0.1347, 0.5981, 0.8745],
        [0.9154, 0.8624, 0.9261],
        [0.0936, 0.3879, 0.4405],
        [0.2849, 0.6233, 0.3540],
        [0.9046, 0.8766, 0.6395]])
x[:, 1] =  tensor([0.5981, 0.8624, 0.3879, 0.6233, 0.8766])


### 6. Reshape 

In [32]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [33]:
print("x = ", x)
print("y = ", y)
print("z = ", z)

x =  tensor([[-0.2502,  0.1915,  0.3381, -0.7789],
        [ 0.7229, -0.5708, -1.9750, -0.8464],
        [-1.1374, -0.3648,  0.0116,  0.2938],
        [ 0.4408,  0.1178, -0.2242,  0.9510]])
y =  tensor([-0.2502,  0.1915,  0.3381, -0.7789,  0.7229, -0.5708, -1.9750, -0.8464,
        -1.1374, -0.3648,  0.0116,  0.2938,  0.4408,  0.1178, -0.2242,  0.9510])
z =  tensor([[-0.2502,  0.1915,  0.3381, -0.7789,  0.7229, -0.5708, -1.9750, -0.8464],
        [-1.1374, -0.3648,  0.0116,  0.2938,  0.4408,  0.1178, -0.2242,  0.9510]])


In [34]:
print(z.shape)

torch.Size([2, 8])


### 7. If you have a one element tensor, use .item() to get the value as a Python number

In [35]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.6901])
1.690146565437317
