# Pytorch Utility Collections

In [3]:
import torch
import numpy as np
import torch.nn as nn

## 1. permute(dims)

将 tensor 的维度换位

**例子：**

In [4]:
x = torch.randn(2, 3, 5)
print(x)
print("\n =======================================\n")
print(x.size())

tensor([[[ 0.7954, -0.6824,  0.1403, -0.6159, -0.5541],
         [ 1.7226,  2.2406, -0.3884, -2.0875, -0.6925],
         [ 1.0914, -1.1086, -0.6361,  0.7487, -0.9169]],

        [[ 0.8438,  2.1555, -1.2703,  0.5627,  1.7565],
         [ 0.0372, -0.5182,  0.3669,  1.5200, -0.4676],
         [-0.5748,  1.3633,  2.3884, -0.0123, -0.4354]]])


torch.Size([2, 3, 5])


In [5]:
x_perm = x.permute(2, 0, 1)
print(x_perm)
print("\n =======================================\n")
print(x_perm.size())

tensor([[[ 0.7954,  1.7226,  1.0914],
         [ 0.8438,  0.0372, -0.5748]],

        [[-0.6824,  2.2406, -1.1086],
         [ 2.1555, -0.5182,  1.3633]],

        [[ 0.1403, -0.3884, -0.6361],
         [-1.2703,  0.3669,  2.3884]],

        [[-0.6159, -2.0875,  0.7487],
         [ 0.5627,  1.5200, -0.0123]],

        [[-0.5541, -0.6925, -0.9169],
         [ 1.7565, -0.4676, -0.4354]]])


torch.Size([5, 2, 3])


## 2. torch.randn

torch.randn(*size, out=None) -> Tensor

**例子：**

In [6]:
a = torch.randn(4)
print(a)
print(a.size())
print("==================\n")

b = torch.rand(1, 4)
print(b)
print(b.size())

tensor([ 1.4654,  0.1855, -0.7807, -0.6112])
torch.Size([4])

tensor([[0.7532, 0.0989, 0.7238, 0.6656]])
torch.Size([1, 4])


## 3. view(size)

In [7]:
b.view(4, -1)

tensor([[0.7532],
        [0.0989],
        [0.7238],
        [0.6656]])

## 4. nn.Conv2d()

> class torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True)

**参数说明**


- in_channels (int) – 输入特征矩阵的通道数 Cin


- out_channels (int) – 输出特征矩阵的通道数 Cout


- kernel_size (int or tuple) – 卷积核的大小


- stride (int or tuple, optional) – 卷积核的步长. 默认: 1


- padding (int or tuple, optional) – 边缘的扩充，使用0进行扩充 Default: 0


- dilation (int or tuple, optional) – 内核之间的距离. Default: 1


- groups (int, optional) – Number of blocked connections from input channels to output channels. Default: 1


- bias (bool, optional) – If True, adds a learnable bias to the output. Default: True

## 5. nn.MaxPool2d()

> class torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False)

**参数说明：**

- kernel_size(int or tuple) - max pooling的窗口大小

- stride(int or tuple, optional) - max pooling的窗口移动的步长。默认值是kernel_size

- padding(int or tuple, optional) - 输入的每一条边补充0的层数

- dilation(int or tuple, optional) – 一个控制窗口中元素步幅的参数

- return_indices - 如果等于True，会返回输出最大值的序号，对于上采样操作会有帮助

- ceil_mode - 如果等于True，计算输出信号大小的时候，会使用向上取整，代替默认的向下取整的操作

## 6. nn.BatchNorm2d()

> torch.nn.BatchNorm2d(num_features, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

**参数说明:**

- num_features： 来自期望输入的特征数，该期望输入的大小为'batch_size x num_features x height x width'

- eps： 为保证数值稳定性（分母不能趋近或取0）,给分母加上的值。默认为1e-5。

- momentum： 动态均值和动态方差所使用的动量。默认为0.1。

- affine： 一个布尔值，当设为true，给该层添加可学习的仿射变换参数。

## 7. nn.Linear()

> class torch.nn.Linear(in_features, out_features, bias=True)

**参数说明：**

- in_features - 每个输入样本的大小

- out_features - 每个输出样本的大小

- bias - 若设置为False，这层不会学习偏置。默认值：True


## 8. SubsetRandomSampler(indices)

> class torch.utils.data.sampler.SubsetRandomSampler(indices)

**函数作用：**

- 样本元素从指定的索引列表中随机抽取，没有替换。

**参数说明：**

- indices: 表示列表的索引

## 9. kaiming_normal()

> torch.nn.init.kaiming_normal(tensor, a=0, mode='fan_in')

**函数作用：**

- 根据He, K等人在“Delving deep into rectifiers: Surpassing human-level performance on ImageNet classification”中描述的方法，用一个正态分布生成值，填充输入的张量或变量。结果张量中的值采样自均值为0，标准差为 $\sqrt{\frac{2}{(1 + a^2) * fan_{in}}}$ 的正态分布。

**参数说明：**

- tensor – n维的torch.Tensor或 autograd.Variable
- a -这层之后使用的rectifier的斜率系数（ReLU的默认值为0）
- mode -可以为“fan_in”（默认）或“fan_out”。“fan_in”保留前向传播时权值方差的量级，“fan_out”保留反向传播时的量级。


**例子如下：**

In [4]:
w = torch.Tensor(3, 5)
nn.init.kaiming_normal(w, mode='fan_out')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  


tensor([[ 1.2340, -2.0492,  0.9643, -0.8630,  0.7096],
        [ 1.2771, -0.0929, -0.0151, -1.3038, -0.6973],
        [ 0.6268, -0.6731, -0.5713, -0.8125, -0.0780]])

## 10. pack_padded_sequence

> torch.nn.utils.rnn.pack_padded_sequence(input, lengths, batch_first=False, enforce_sorted=True)

**函数作用**
- 压缩填充后的序列

**参数说明**

- input（Tensor）- 压缩后的可变长序列。其 size 可为 $T \times B \times *$。T 为最长序列的长度，B是 batch size，* 为任意维度的数值（包括0）

- lengths (Tensor) - 每个 batch 中序列长度构成的列表

- batch_first (bool, optional) - if True，input 则为 $B \times T \times *$ 格式

- enforce_sorted (bool, optional) - if True, input 则按照长度大小降序排列

## 11. pad_packed_sequence

> torch.nn.utils.rnn.pad_packed_sequence(sequence, batch_first=False, padding_value=0.0, total_length=None)

**函数作用**

填充一个压缩的可变长序列

**参数说明**

- sequence (PackedSequence) - 要填充的batch

- batch_first (bool, optional) - if True, 结果是 $B \times T \times *$ 格式

- padding_value (float, optional) - 填充元素的值

- total_length (int, optional) - if not None, 结果会被填充为 total_length 长度